// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/blockchain.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Block struct {
	PrvHash              string   `protobuf:"bytes,1,opt,name=prvHash,proto3" json:"prvHash,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Hash                 string   `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_10df223d4102c3ff, []int{0}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetPrvHash() string {
	if m != nil {
		return m.PrvHash
	}
	return ""
}

func (m *Block) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Block) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type BlockRequest struct {
	Size                 int32    `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRequest) Reset()         { *m = BlockRequest{} }
func (m *BlockRequest) String() string { return proto.CompactTextString(m) }
func (*BlockRequest) ProtoMessage()    {}
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_10df223d4102c3ff, []int{1}
}
func (m *BlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequest.Unmarshal(m, b)
}
func (m *BlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequest.Marshal(b, m, deterministic)
}
func (dst *BlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequest.Merge(dst, src)
}
func (m *BlockRequest) XXX_Size() int {
	return xxx_messageInfo_BlockRequest.Size(m)
}
func (m *BlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequest proto.InternalMessageInfo

func (m *BlockRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type BlockResponce struct {
	Size                 int32    `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockResponce) Reset()         { *m = BlockResponce{} }
func (m *BlockResponce) String() string { return proto.CompactTextString(m) }
func (*BlockResponce) ProtoMessage()    {}
func (*BlockResponce) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_10df223d4102c3ff, []int{2}
}
func (m *BlockResponce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockResponce.Unmarshal(m, b)
}
func (m *BlockResponce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockResponce.Marshal(b, m, deterministic)
}
func (dst *BlockResponce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockResponce.Merge(dst, src)
}
func (m *BlockResponce) XXX_Size() int {
	return xxx_messageInfo_BlockResponce.Size(m)
}
func (m *BlockResponce) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockResponce.DiscardUnknown(m)
}

var xxx_messageInfo_BlockResponce proto.InternalMessageInfo

func (m *BlockResponce) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type ChainRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainRequest) Reset()         { *m = ChainRequest{} }
func (m *ChainRequest) String() string { return proto.CompactTextString(m) }
func (*ChainRequest) ProtoMessage()    {}
func (*ChainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_10df223d4102c3ff, []int{3}
}
func (m *ChainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainRequest.Unmarshal(m, b)
}
func (m *ChainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainRequest.Marshal(b, m, deterministic)
}
func (dst *ChainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainRequest.Merge(dst, src)
}
func (m *ChainRequest) XXX_Size() int {
	return xxx_messageInfo_ChainRequest.Size(m)
}
func (m *ChainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChainRequest proto.InternalMessageInfo

type ChainResponce struct {
	Block                []*Block `protobuf:"bytes,1,rep,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainResponce) Reset()         { *m = ChainResponce{} }
func (m *ChainResponce) String() string { return proto.CompactTextString(m) }
func (*ChainResponce) ProtoMessage()    {}
func (*ChainResponce) Descriptor() ([]byte, []int) {
	return fileDescriptor_blockchain_10df223d4102c3ff, []int{4}
}
func (m *ChainResponce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainResponce.Unmarshal(m, b)
}
func (m *ChainResponce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainResponce.Marshal(b, m, deterministic)
}
func (dst *ChainResponce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainResponce.Merge(dst, src)
}
func (m *ChainResponce) XXX_Size() int {
	return xxx_messageInfo_ChainResponce.Size(m)
}
func (m *ChainResponce) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainResponce.DiscardUnknown(m)
}

var xxx_messageInfo_ChainResponce proto.InternalMessageInfo

func (m *ChainResponce) GetBlock() []*Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func init() {
	proto.RegisterType((*Block)(nil), "proto.Block")
	proto.RegisterType((*BlockRequest)(nil), "proto.BlockRequest")
	proto.RegisterType((*BlockResponce)(nil), "proto.BlockResponce")
	proto.RegisterType((*ChainRequest)(nil), "proto.ChainRequest")
	proto.RegisterType((*ChainResponce)(nil), "proto.ChainResponce")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlockchainServiceClient is the client API for BlockchainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlockchainServiceClient interface {
	AddBlocks(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (*BlockResponce, error)
	GetChain(ctx context.Context, in *ChainRequest, opts ...grpc.CallOption) (*ChainResponce, error)
}

type blockchainServiceClient struct {
	cc *grpc.ClientConn
}

func NewBlockchainServiceClient(cc *grpc.ClientConn) BlockchainServiceClient {
	return &blockchainServiceClient{cc}
}

func (c *blockchainServiceClient) AddBlocks(ctx context.Context, in *BlockRequest, opts ...grpc.CallOption) (*BlockResponce, error) {
	out := new(BlockResponce)
	err := c.cc.Invoke(ctx, "/proto.BlockchainService/addBlocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainServiceClient) GetChain(ctx context.Context, in *ChainRequest, opts ...grpc.CallOption) (*ChainResponce, error) {
	out := new(ChainResponce)
	err := c.cc.Invoke(ctx, "/proto.BlockchainService/getChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockchainServiceServer is the server API for BlockchainService service.
type BlockchainServiceServer interface {
	AddBlocks(context.Context, *BlockRequest) (*BlockResponce, error)
	GetChain(context.Context, *ChainRequest) (*ChainResponce, error)
}

func RegisterBlockchainServiceServer(s *grpc.Server, srv BlockchainServiceServer) {
	s.RegisterService(&_BlockchainService_serviceDesc, srv)
}

func _BlockchainService_AddBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServiceServer).AddBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BlockchainService/AddBlocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServiceServer).AddBlocks(ctx, req.(*BlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainService_GetChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServiceServer).GetChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BlockchainService/GetChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServiceServer).GetChain(ctx, req.(*ChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlockchainService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BlockchainService",
	HandlerType: (*BlockchainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addBlocks",
			Handler:    _BlockchainService_AddBlocks_Handler,
		},
		{
			MethodName: "getChain",
			Handler:    _BlockchainService_GetChain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/blockchain.proto",
}

func init() { proto.RegisterFile("proto/blockchain.proto", fileDescriptor_blockchain_10df223d4102c3ff) }

var fileDescriptor_blockchain_10df223d4102c3ff = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x6b, 0x8a, 0x81, 0x1e, 0x29, 0x12, 0x06, 0x21, 0x8b, 0xa9, 0x3a, 0x96, 0x4e, 0x45,
	0x6a, 0x06, 0x98, 0xc3, 0x02, 0x6b, 0xf8, 0x05, 0x8e, 0x63, 0x91, 0x08, 0x14, 0x87, 0xd8, 0x64,
	0xe0, 0x07, 0xf0, 0xbb, 0x91, 0xcf, 0x26, 0x22, 0x52, 0x27, 0x9f, 0x3f, 0xbf, 0xf7, 0xfc, 0x0e,
	0x6e, 0xfa, 0xc1, 0x7a, 0x7b, 0x5f, 0x7d, 0x58, 0xfd, 0xae, 0x1b, 0xd5, 0x76, 0x3b, 0x02, 0x82,
	0xd3, 0x81, 0x2f, 0xc0, 0x8b, 0xf0, 0x24, 0x24, 0x9c, 0xf6, 0xc3, 0xf8, 0xac, 0x5c, 0x23, 0xd9,
	0x86, 0x6d, 0x57, 0xe5, 0xdf, 0x55, 0x08, 0x38, 0xae, 0x95, 0x57, 0xf2, 0x88, 0x30, 0xcd, 0x81,
	0x35, 0x41, 0xba, 0x8c, 0x2c, 0xcc, 0x88, 0x90, 0x51, 0x54, 0x69, 0x3e, 0xbf, 0x8c, 0xf3, 0x41,
	0xe3, 0xda, 0x6f, 0x43, 0x71, 0xbc, 0xa4, 0x19, 0xef, 0x60, 0x9d, 0x34, 0xae, 0xb7, 0x9d, 0x36,
	0x07, 0x45, 0x17, 0x90, 0x3d, 0x85, 0xa6, 0x29, 0x08, 0x73, 0x58, 0xa7, 0x7b, 0x32, 0x21, 0x70,
	0xda, 0x47, 0xb2, 0xcd, 0x72, 0x7b, 0xbe, 0xcf, 0xe2, 0x4a, 0xbb, 0x98, 0x1c, 0x9f, 0xf6, 0x3f,
	0x0c, 0x2e, 0x8b, 0x69, 0xe9, 0x57, 0x33, 0x8c, 0xad, 0x36, 0xe2, 0x11, 0x56, 0xaa, 0xae, 0x89,
	0x3b, 0x71, 0x35, 0xf3, 0xc5, 0xcf, 0x6e, 0xaf, 0xe7, 0x30, 0xfe, 0x88, 0x0b, 0xf1, 0x00, 0x67,
	0x6f, 0xc6, 0x53, 0x8f, 0xc9, 0xf8, 0xbf, 0xe5, 0x64, 0x9c, 0x55, 0xc5, 0x45, 0x75, 0x42, 0x38,
	0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x6e, 0xc6, 0x7c, 0x09, 0x89, 0x01, 0x00, 0x00,
}
